global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hospital-management'
    static_configs:
      - targets: ['hospital-management:8093']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'hospital-webhook'
    static_configs:
      - targets: ['hospital-webhook:8094']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s
