spring:
  application:
    name: HospitalwebHook
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8094

logging:
  level:
    com.example.HospitalwebHook: INFO
    org.springframework.kafka: INFO
